### ISSUE TITLE
res.rows.length undefined when exceed 1000

### ISSUE THREAD

**Issue by alaaapp** [nolanlawson/cordova-plugin-sqlite-2#41]
Hi, 
First thank you for this great plugin, its helping me alot.
The issue is described in the title. it's really strange...although i can get all data using LIMIT statement by slicing, any help? 
thx, Al

**Comment by nolanlawson** [comment]
Can you provide more detail or a test case to reproduce?

**Comment by gevyaniv** [comment]
Hello Nolan,

I am a big fan of your work and I wanted to thank you.

Maybe I can provide a few more details. 
I have been using this plugin for a while, and recently, while working with a big document in the DB,  I got this error message

`Uncaught TypeError: Cannot read property 'length' of null                               cordova.js:314 
safeJsonParse 		 	   @ pouchdb.js:3979

(anonymous function) 	   @ pouchdb.js:6865

(anonymous function) 	   @ sqlite-plugin.js:4439

onSuccess 			   @ sqlite-plugin.js:4741

callbackFromNative 	   @ cordova.js:293

processMessage 		   @ cordova.js:1081

processMessages 	 	   @ cordova.js:1104

pollOnce 			 	   @ cordova.js:973

pollOnceFromOnlineEvent @ cordova.js:960`

It seems like when reading a big document, the success callback is being called with empty result which causes this error.

I tried a different plugin and it worked, but I was really hoping this can be fixed since we have been using your plugin for a while and we prefer it.

I hope this helps

**Comment by nolanlawson** [comment]
Which version of Android? Also could be related to #39 .

**Comment by nolanlawson** [comment]
Closing old issues, please reopen if there is a test case or details that can reproduce this.

**Comment by nolanlawson** [comment]
also this may be the core issue: https://github.com/nolanlawson/cordova-plugin-sqlite-2/issues/46
